datasets:
  ETTh1:
    root_path: ./dataset/ETT-small/
    data_path: ETTh1.csv
    data_name: etth1
    data: ett_h
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  ETTh2:
    root_path: ./dataset/ETT-small/
    data_path: ETTh2.csv
    data_name: etth2
    data: ett_h
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  ETTm1:
    root_path: ./dataset/ETT-small/
    data_path: ETTm1.csv
    data_name: ettm1
    data: ett_m
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  ETTm2:
    root_path: ./dataset/ETT-small/
    data_path: ETTm2.csv
    data_name: ettm2
    data: ett_m
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  traffic:
    root_path: ./dataset/traffic/
    data_path: traffic.csv
    data_name: traffic
    data: custom
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  weather:
    root_path: ./dataset/weather/
    data_path: weather.csv
    data_name: weather
    data: custom
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  electricity:
    root_path: ./dataset/electricity/
    data_path: electricity.csv
    data_name: electricity
    data: custom
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  ILI:
    root_path: ./dataset/illness/
    data_path: national_illness.csv
    data_name: ILI
    data: custom
    lradj: type4 
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100 
  exchange:
    root_path: ./dataset/exchange_rate/
    data_path: exchange_rate.csv
    data_name: exchange
    data: custom
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  monash:
    root_path: ./datasets/Monash_small/
    data_path: monash.csv
    data_name: monash
    data: monash
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  FaceDetection:
    root_path: ./dataset/FaceDetection/
    data_path: FaceDetection_TRAIN.ts
    data_name: FaceDetection
    data: UEA
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  Heartbeat:
    root_path: ./dataset/Heartbeat/
    data_path: Heartbeat_TRAIN.ts
    data_name: Heartbeat
    data: UEA
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  SpokenArabicDigits:
    root_path: ./dataset/SpokenArabicDigits/
    data_path: SpokenArabicDigits_TRAIN.ts
    data_name: SpokenArabicDigits
    data: UEA
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  EthanolConcentration:
    root_path: ./dataset/EthanolConcentration/
    data_path: EthanolConcentration_TRAIN.ts
    data_name: EthanolConcentration
    data: UEA
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  Handwriting:
    root_path: ./dataset/Handwriting/
    data_path: Handwriting_TRAIN.ts
    data_name: Handwriting
    data: UEA
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  JapaneseVowels:
    root_path: ./dataset/JapaneseVowels/
    data_path: JapaneseVowels_TRAIN.ts
    data_name: JapaneseVowels
    data: UEA
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  PEMS-SF:
    root_path: ./dataset/PEMS-SF/
    data_path: PEMS-SF_TRAIN.ts
    data_name: PEMS-SF
    data: UEA
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  SelfRegulationSCP1:
    root_path: ./dataset/SelfRegulationSCP1/
    data_path: SelfRegulationSCP1_TRAIN.ts
    data_name: SelfRegulationSCP1
    data: UEA
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  SelfRegulationSCP2:
    root_path: ./dataset/SelfRegulationSCP2/
    data_path: SelfRegulationSCP2_TRAIN.ts
    data_name: SelfRegulationSCP2
    data: UEA
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  UWaveGestureLibrary:
    root_path: ./dataset/UWaveGestureLibrary/
    data_path: UWaveGestureLibrary_TRAIN.ts
    data_name: UWaveGestureLibrary
    data: UEA
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  